// ================================================================================================================= //
//                                                                                                                   //
//                                                     Héraldix                                                      //
//                                                                                                                   //
// ================================================================================================================= //

profils = {
	// "**": {},
	"Royaume de France": {
		"Roi": {
			"collier": ["RF", "Ordre de Saint-Michel"],
			"couronne": ["RF", "Roi"],
			"cri": ["**", "Montjoie ! Saint Denis !"],
			"devise": ["**", "Lilia non laborant neque nent"],
			"écu": ["RF", "France"],
			"heaume": ["RF", "Roi"],
			"manteau": ["RF", "France"],
			"couronne-manteau": ["RF", "Roi"],
			"portant-dextre": ["**", "Ange"],
			"portant-senestre": ["**", "Ange"],
		},
		"Dauphin": {
			"collier": ["**", ""],
			"couronne": ["RF", "Dauphin"],
			"cri": ["**", "Montjoie ! Saint Denis !"],
			"devise": ["**", "Lilia non laborant neque nent"],
			"écu": ["RF", "Dauphin"],
			"heaume": ["RF", "Roi"],
			"manteau": ["RF", "France"],
			"couronne-manteau": ["RF", "Dauphin"],
			"portant-dextre": ["**", "Ange"],
			"portant-senestre": ["**", "Ange"],
		},
		"Fils": {
			"collier": ["**", ""],
			"couronne": ["RF", "Fils"],
			"cri": ["**", "Montjoie ! Saint Denis !"],
			"devise": ["**", "Lilia non laborant neque nent"],
			"écu": ["RF", "France"],
			"heaume": ["RF", "Roi"],
			"manteau": ["RF", "France"],
			"couronne-manteau": ["RF", "Fils"],
			"portant-dextre": ["**", "Ange"],
			"portant-senestre": ["**", "Ange"],
		},
		"Petit-fils": {
			"collier": ["**", ""],
			"couronne": ["RF", "Petit-fils"],
			"cri": ["**", "Montjoie ! Saint Denis !"],
			"devise": ["**", "Lilia non laborant neque nent"],
			"écu": ["RF", "France"],
			"heaume": ["RF", "Roi"],
			"manteau": ["RF", "France"],
			"couronne-manteau": ["RF", "Petit-fils"],
			"portant-dextre": ["**", "Ange"],
			"portant-senestre": ["**", "Ange"],
		},
		"Prince": {
			"collier": ["**", ""],
			"couronne": ["RF", "Prince"],
			"cri": ["**", "Montjoie ! Saint Denis !"],
			"devise": ["**", "Lilia non laborant neque nent"],
			"écu": ["RF", "France"],
			"heaume": ["RF", "Prince"],
			"manteau": ["RF", "France"],
			"couronne-manteau": ["RF", "Prince"],
			"portant-dextre": ["**", "Ange"],
			"portant-senestre": ["**", "Ange"],
		},
		"Duc souverain et pair": {
			"collier": ["**", ""],
			"couronne": ["RF", "Duc et pair"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Prince"],
			"manteau": ["RF", "Pair"],
			"couronne-manteau": ["RF", "Duc et pair"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Duc souverain": {
			"collier": ["**", ""],
			"couronne": ["RF", "Duc"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Prince"],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Duc et pair": {
			"collier": ["**", ""],
			"couronne": ["RF", "Duc et pair"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Duc"],
			"manteau": ["RF", "Pair"],
			"couronne-manteau": ["RF", "Duc et pair"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Duc": {
			"collier": ["**", ""],
			"couronne": ["RF", "Duc"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Duc"],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Marquis et pair": {
			"collier": ["**", ""],
			"couronne": ["RF", "Marquis et pair"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Marquis"],
			"manteau": ["RF", "Pair"],
			"couronne-manteau": ["RF", "Marquis et pair"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Marquis": {
			"collier": ["**", ""],
			"couronne": ["RF", "Marquis"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Marquis"],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Comte et pair": {
			"collier": ["**", ""],
			"couronne": ["RF", "Comte et pair"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Comte"],
			"manteau": ["RF", "Pair"],
			"couronne-manteau": ["RF", "Comte et pair"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Comte": {
			"collier": ["**", ""],
			"couronne": ["RF", "Comte"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Comte"],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Vicomte et pair": {
			"collier": ["**", ""],
			"couronne": ["RF", "Vicomte et pair"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Comte"],
			"manteau": ["RF", "Pair"],
			"couronne-manteau": ["RF", "Vicomte et pair"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Vicomte": {
			"collier": ["**", ""],
			"couronne": ["RF", "Vicomte"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Comte"],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Vidame": {
			"collier": ["**", ""],
			"couronne": ["RF", "Vidame"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Comte"],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Baron et pair": {
			"collier": ["**", ""],
			"couronne": ["RF", "Baron et pair"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Baron"],
			"manteau": ["RF", "Pair"],
			"couronne-manteau": ["RF", "Baron et pair"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Baron": {
			"collier": ["**", ""],
			"couronne": ["RF", "Baron"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Baron"],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		/* "Gentilhomme d'ancienne race": {
			"collier": ["**", ""],
			"couronne": ["**", ""],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Gentilhomme d'ancienne race"],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		}, */
		/* "Banneret": {
			"collier": ["**", ""],
			"couronne": ["RF", "Banneret"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		}, */
		/* "Chevalier": {
			"collier": ["**", ""],
			"couronne": ["RF", "Chevalier"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},*/
		/* "Gentilhomme de trois races": {
			"collier": ["**", ""],
			"couronne": ["**", ""],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Gentilhomme d'ancienne race"],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		}, */
		/*"Anobli": {
			"collier": ["**", ""],
			"couronne": ["**", ""],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Anobli"],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},*/
		/*"Bâtard": {
			"collier": ["**", ""],
			"couronne": ["**", ""],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Bâtard"],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},*/
	},
	"Empire français": {
		"Empereur 1804": {
			"collier": ["EF", "Ordre de la Légion d'honneur"],
			"couronne": ["EF", "Empereur 1804"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["EF", "Empire"],
			"heaume": ["RF", "Roi"],
			"manteau": ["EF", "Empire"],
			"couronne-manteau": ["EF", "Empereur 1804"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		// "Empereur 1852": {},
		// "Prince souverain": {},
		// "Prince": {},
		// "Duc": {},
		// "Comte": {},
		// "Baron": {},
		// "Chevalier": {},
		// "Grand dignitaire": {},
	},
	"Villes françaises": {
		"Capitale": {
			"collier": ["**", ""],
			"couronne": ["VF", "Capitale"],
			"cri": ["**", ""],
			"devise": ["**", "Fluctuat nec mergitur"],
			"écu": ["VF", "Paris"],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		/*"Chef-lieu": {
			"collier": ["**", ""],
			"couronne": ["VF", "Chef-lieu"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},*/
		/*"Commune": {
			"collier": ["**", ""],
			"couronne": ["VF", "Commune"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},*/
	},
	"Royaume d'Espagne": {
		"Roi": {
			"collier": ["RE", "Ordre de la Toison d'or"],
			"couronne": ["RE", "Roi"],
			"cri": ["**", "Una grande libre"],
			"devise": ["**", "Plus ultra"],
			"écu": ["RE", "Espagne"],
			"heaume": ["**", ""],
			"manteau": ["RE", "Grand"],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Grand": {
			"collier": ["**", ""],
			"couronne": ["RE", "Grand"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["**", ""],
			"manteau": ["RE", "Grand"],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
	},
	"Royaume-Uni": {
		"Roi": {
			"collier": ["RU", "Ordre de la Jarretière"],
			"couronne": ["RU", "Roi"],
			"cri": ["**", ""],
			"devise": ["**", "Dieu et mon droit"],
			"écu": ["RU", "Royaume"],
			"heaume": ["RU", "Roi"],
			"manteau": ["**", ""],
			"couronne-manteau": ["RU", "Roi"],
			"portant-dextre": ["**", "Lion"],
			"portant-senestre": ["**", "Licorne"],
		},
		// "Duc": {},
		// "Marquis": {},
		// "Comte": {},
		// "Vicomte": {},
		// "Baron": {},
		// "Baronnet": {},
		// "Gentilhomme": {},
	},
	"Saint-Empire romain germanique": {
		"Empereur": {
			"collier": ["**", ""],
			"couronne": ["ER", "Empereur"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["ER", "Empire"],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Prince": {
			"collier": ["**", ""],
			"couronne": ["ER", "Prince"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["**", ""],
			"manteau": ["**", "Rouge"],
			"couronne-manteau": ["ER", "Prince"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
	},
	"État du Vatican": {
		"Pape": {
			"collier": ["**", ""],
			"couronne": ["EV", "Pape"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["EV", "État du Vatican"],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
	},
	"Royaume du Portugal": {
		"Roi": {
			"collier": ["**", ""],
			"couronne": ["RP", "Roi"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["RP", "Portugal"],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"couronne-manteau": ["RP", "Roi"],
			"portant-dextre": ["**", "Dragon"],
			"portant-senestre": ["**", "Dragon"],
		},
	},
	"Grand-Duché de Luxembourg": {
		"Grand-Duc": {
			"collier": ["**", ""],
			"couronne": ["GL", "Grand-Duc"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["GL", "Luxembourg"],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"couronne-manteau": ["GL", "Grand-Duc"],
			"portant-dextre": ["**", "Lion"],
			"portant-senestre": ["**", "Lion"],
		},
	},
	"Royaume de Suède": {
		"Roi": {
			"collier": ["**", ""],
			"couronne": ["RS", "Roi"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["RS", "Suède"],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"couronne-manteau": ["RS", "Roi"],
			"portant-dextre": ["**", "Lion"],
			"portant-senestre": ["**", "Lion"],
		},
	},
	"Royaume de Jérusalem": {
		"Ordre équestre du Saint-Sépulcre": {
			"collier": ["**", ""],
			"couronne": ["RJ", "Couronne d'épines"],
			"cri": ["**", ""],
			"devise": ["**", "Deus lo vult"],
			"écu": ["RJ", "Ordre équestre du Saint-Sépulcre"],
			"heaume": ["RJ", "Roi"],
			"manteau": ["**", ""],
			"couronne-manteau": ["**", ""],
			"portant-dextre": ["**", "Ange"],
			"portant-senestre": ["**", "Ange"],
		},
	},
};

// ================================================================================================================= //
//                                                                                                                   //
//                                                     Héraldix                                                      //
//                                                                                                                   //
// ================================================================================================================= //