// ================================================================================================================= //
//                                                                                                                   //
//                                                     Héraldix                                                      //
//                                                                                                                   //
// ================================================================================================================= //

profils = {
	"Royaume de France": {
		"Roi": {
			"collier": ["RF", "Ordre de Saint-Michel"],
			"couronne": ["RF", "Roi"],
			"cri": ["**", "Montjoie ! Saint Denis !"],
			"devise": ["**", "Lilia non laborant neque nent"],
			"écu": ["RF", "France"],
			"heaume": ["RF", "Roi"],
			"manteau": ["RF", "France"],
			"portant-dextre": ["**", "Ange"],
			"portant-senestre": ["**", "Ange"],
		},
		"Dauphin": {
			"collier": ["**", ""],
			"couronne": ["RF", "Dauphin"],
			"cri": ["**", "Montjoie ! Saint Denis !"],
			"devise": ["**", "Lilia non laborant neque nent"],
			"écu": ["RF", "France"],
			"heaume": ["RF", "Roi"],
			"manteau": ["RF", "France"],
			"portant-dextre": ["**", "Ange"],
			"portant-senestre": ["**", "Ange"],
		},
		"Fils": {
			"collier": ["**", ""],
			"couronne": ["RF", "Fils"],
			"cri": ["**", "Montjoie ! Saint Denis !"],
			"devise": ["**", "Lilia non laborant neque nent"],
			"écu": ["RF", "France"],
			"heaume": ["RF", "Roi"],
			"manteau": ["RF", "France"],
			"portant-dextre": ["**", "Ange"],
			"portant-senestre": ["**", "Ange"],
		},
		"Petit-fils": {
			"collier": ["**", ""],
			"couronne": ["RF", "Petit-fils"],
			"cri": ["**", "Montjoie ! Saint Denis !"],
			"devise": ["**", "Lilia non laborant neque nent"],
			"écu": ["RF", "France"],
			"heaume": ["RF", "Roi"],
			"manteau": ["RF", "France"],
			"portant-dextre": ["**", "Ange"],
			"portant-senestre": ["**", "Ange"],
		},
		"Prince": {
			"collier": ["**", ""],
			"couronne": ["RF", "Prince"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["RF", "France"],
			"heaume": ["RF", "Prince"],
			"manteau": ["RF", "France"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Duc souverain et pair": {
			"collier": ["**", ""],
			"couronne": ["RF", "Duc"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Prince"],
			"manteau": ["RF", "Pair"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Duc souverain": {
			"collier": ["**", ""],
			"couronne": ["RF", "Duc"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Prince"],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Duc et pair": {
			"collier": ["**", ""],
			"couronne": ["RF", "Duc"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Duc"],
			"manteau": ["RF", "Pair"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Duc": {
			"collier": ["**", ""],
			"couronne": ["RF", "Duc"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Duc"],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Marquis et pair": {
			"collier": ["**", ""],
			"couronne": ["RF", "Marquis et pair"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Marquis"],
			"manteau": ["RF", "Pair"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Marquis": {
			"collier": ["**", ""],
			"couronne": ["RF", "Marquis"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Marquis"],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Comte et pair": {
			"collier": ["**", ""],
			"couronne": ["RF", "Comte et pair"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Comte"],
			"manteau": ["RF", "Pair"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Comte": {
			"collier": ["**", ""],
			"couronne": ["RF", "Comte"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Comte"],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Vicomte": {
			"collier": ["**", ""],
			"couronne": ["RF", "Vicomte"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Comte"],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Vidame": {
			"collier": ["**", ""],
			"couronne": ["RF", "Vidame"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Comte"],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Baron et pair": {
			"collier": ["**", ""],
			"couronne": ["RF", "Baron et pair"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Baron"],
			"manteau": ["RF", "Pair"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Baron": {
			"collier": ["**", ""],
			"couronne": ["RF", "Baron"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Baron"],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Banneret": {
			"collier": ["**", ""],
			"couronne": ["RF", "Banneret"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Chevalier": {
			"collier": ["**", ""],
			"couronne": ["RF", "Chevalier"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Anobli": {
			"collier": ["**", ""],
			"couronne": ["**", ""],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Anobli"],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Bâtard": {
			"collier": ["**", ""],
			"couronne": ["**", ""],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["RF", "Bâtard"],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
	},
	"Empire français": {
		"Empereur 1804": {
			"collier": ["**", ""],
			"couronne": ["EF", "Empereur 1804"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["EF", "Bonaparte"],
			"heaume": ["RF", "Roi"],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
	},
	"Villes françaises": {
		"Paris": {
			"collier": ["**", ""],
			"couronne": ["VF", "Capitale"],
			"cri": ["**", ""],
			"devise": ["**", "Fluctuat nec mergitur"],
			"écu": ["VF", "Paris"],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Capitale": {
			"collier": ["**", ""],
			"couronne": ["VF", "Capitale"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Chef-lieu": {
			"collier": ["**", ""],
			"couronne": ["VF", "Chef-lieu"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Commune": {
			"collier": ["**", ""],
			"couronne": ["VF", "Commune"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["**", ""],
			"manteau": ["**", ""],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
	},
	"Reino de España": {
		"Rey": {
			"collier": ["RE", "Orden del Toisón de Oro"],
			"couronne": ["RE", "Rey de España"],
			"cri": ["**", "Una grande libre"],
			"devise": ["**", "Plus ultra"],
			"écu": ["RE", "España"],
			"heaume": ["**", ""],
			"manteau": ["RE", "Grande"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
		"Grande": {
			"collier": ["**", ""],
			"couronne": ["RE", "Grande"],
			"cri": ["**", ""],
			"devise": ["**", ""],
			"écu": ["**", ""],
			"heaume": ["**", ""],
			"manteau": ["RE", "Grande"],
			"portant-dextre": ["**", ""],
			"portant-senestre": ["**", ""],
		},
	},
	"United Kingdom": {
		"King": {
			"collier": ["**", ""],
			"couronne": ["UK", "King"],
			"cri": ["**", ""],
			"devise": ["**", "Dieu et mon droit"],
			"écu": ["UK", "Kingdom"],
			"heaume": ["UK", "King"],
			"manteau": ["**", ""],
			"portant-dextre": ["**", "Lion"],
			"portant-senestre": ["**", "Licorne"],
		}
	},
	"Heiliges Römisches Reich": {},
	"Status Civitatis Vaticanæ": {},
	"Reino de Portugal": {},
	"Groussherzogtum Lëtzebuerg": {},
	"Konungariket Sverige": {},
};

// ================================================================================================================= //
//                                                                                                                   //
//                                                     Héraldix                                                      //
//                                                                                                                   //
// ================================================================================================================= //